api:
  insecure: true

providers:
  docker:
    network: traefik
  file:
    directory: /config
    watch: true

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
